### ISSUE TITLE
todo - guidage

### ISSUE THREAD

**Issue by skiild** [LogarithmeNeper/IFYouDrive#20]
- [x] les étapes sont skip si trop proche de la précédente (important - priorité de demain matin)
- [ ] supprimer l'overlay derrière le chemin parcouru (peu important / jsp comment faire)
- [x] mieux gérer la fin du guidage / les interruptions de l'application (important - 2ème priorité de demain)
- [ ] éventuellement décrémenter les distances à parcourir de manière plus élégantes, par palier (pas important mais sur waze ils font ça)
